name: Order CI (use Gradle version)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push-order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x ./gradlew

      - name: Create application.properties from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_PROPS_ORDER }}" > src/main/resources/application.properties

      - name: Build order jar
        run: ./gradlew clean bootJar -x test -Dspring.profiles.active=ci

      # Gradle의 version 값을 읽어옴 (예: 1.0.0 또는 1.0.0-SNAPSHOT)
      - name: Read version from Gradle
        id: ver
        run: echo "VERSION=$(./gradlew -q properties | grep '^version:' | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Set image tags
        id: vars
        run: |
          IMAGE="hysungzzang/sampoom"
          VER="${{ steps.ver.outputs.VERSION }}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=order-${VER}" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=order-latest" >> $GITHUB_OUTPUT


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            network=host

      - name: Build & Push (order)
        uses: docker/build-push-action@v6
        env:
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          provenance: false
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_VERSION }}
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_LATEST }}